name: Build and Deploy

# Controls when the action will run. 
on:
 create:
  tags:
    -v* 
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest     # The type of runner that the job will run on (ubuntu)
    steps:  #Represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@master   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Build & Deploy 🚀
        uses: JacksonMaxfield/github-pages-deploy-action-python@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master #The branch the action should deploy from.
          BRANCH: gh-pages # The branch where the action should deploy to.
          FOLDER: docs/_build/html # The folder directory that contain the content that we want to deploy.
          BUILD_SCRIPT: pip install .[all] && make docs-build && touch docs/_build/html/.nojekyll # The build script the action should run prior to deploying.
